# Generated by Django 5.2.3 on 2025-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the contact mail was sent.', null=True),
        ),
    ]
