# Generated by Django 5.2.3 on 2025-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contact_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gmail_thread_id',
            field=models.CharField(blank=True, help_text='Gmail thread ID for direct linking to the conversation.', max_length=255, null=True),
        ),
    ]
