version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=3
    volumes:
      - static_volume:/app/static
      - ./:/app/
    expose:
      - 8000
    # env_file:
    #   - .env

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web

volumes:
  static_volume: 